### ISSUE TITLE
running into issue with CMark in podfile

### ISSUE THREAD

**Issue by ankong987** [contentful-labs/markdown-example-ios#1]
Hi,

When I to execute the project, i get CocoaMarkdown missing. Naturally, I attempt to rebuild the podfile to download missing cocoapods. However when I do, it downloads the cmark cocoapod and it runs into a error. 

[!] /bin/bash -c 
set -e
cat >src/cmark_export.h <<EOF
#define CMARK_EXPORT __attribute__((visibility("default")))
EOF

    cat >src/cmark_version.h <<EOF
#ifndef CMARK_VERSION_H
#define CMARK_VERSION_H

#define CMARK_VERSION ((0 << 16) | (17 << 8)  | 0)
#define CMARK_VERSION_STRING "0.17.0"

#endif
EOF

    cat >src/config.h <<EOF
#define HAVE_STDBOOL_H

#ifdef HAVE_STDBOOL_H
  #include <stdbool.h>
#elif !defined(__cplusplus)
  typedef char bool;
#endif

#define HAVE___BUILTIN_EXPECT

#define HAVE___ATTRIBUTE__

#ifdef HAVE___ATTRIBUTE__
  #define CMARK_ATTRIBUTE(list) __attribute__ (list)
#else
  #define CMARK_ATTRIBUTE(list)
#endif

#define HAVE_VA_COPY

#ifndef HAVE_VA_COPY
  #define va_copy(dest, src) ((dest) = (src))
#endif

#define CMARK_INLINE inline
EOF

    perl tools/mkcasefold.pl < data/CaseFolding-3.2.0.txt > src/case_fold_switch.inc
    re2c --case-insensitive -bis src/scanners.re > src/scanners.c || (rm src/scanners.c && false)

/bin/bash: line 45: re2c: command not found

Any resolution on this would be appreciated, I need it to understand how to integrate markdown from contentful into my project.

Thanks,

Anthony

**Comment by neonichu** [comment]
Seems like `cmark` requires the installation of the third-party `re2c` tool, it can be installed using homebrew: `brew install re2c`. I'll update the `README` to reflect this.
